// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa-DrgyXiElIRmrg5r4a2eU1nRbnLiTNk',
    appId: '1:596493783703:web:6e73643b6c49109e620fd2',
    messagingSenderId: '596493783703',
    projectId: 'n-chat-application-1',
    authDomain: 'n-chat-application-1.firebaseapp.com',
    storageBucket: 'n-chat-application-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs7X4qjmSuk70DH49Mv1udDMyRFCzYIFM',
    appId: '1:596493783703:android:7885b539de078708620fd2',
    messagingSenderId: '596493783703',
    projectId: 'n-chat-application-1',
    storageBucket: 'n-chat-application-1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa-DrgyXiElIRmrg5r4a2eU1nRbnLiTNk',
    appId: '1:596493783703:web:4602c54fe6bdda52620fd2',
    messagingSenderId: '596493783703',
    projectId: 'n-chat-application-1',
    authDomain: 'n-chat-application-1.firebaseapp.com',
    storageBucket: 'n-chat-application-1.firebasestorage.app',
  );

}